In [2]:
import numpy as np

In [4]:
# 1D NUMPY ARRAY
x = np.array([45,67,57,60])
print(x)
print(type(x))
print(x.dtype)

[45 67 57 60]
<class 'numpy.ndarray'>
int32


In [5]:
# verify datatyoe
x = np.array([45,67,57,60,9.8])
print(x)
print(type(x))
print(x.dtype)

[45.  67.  57.  60.   9.8]
<class 'numpy.ndarray'>
float64


In [6]:
# 2D NUMPY ARRAY
x1 = np.array([[20,40],[30,60]])
print(x1)
print(type(x1))
print (x1.shape)

[[20 40]
 [30 60]]
<class 'numpy.ndarray'>
(2, 2)


In [8]:
#reshaping the array
a1 = np.array([10,20,30,40])
a2 = a1.reshape(2,2)
print(a2)
print(a2.shape)

[[10 20]
 [30 40]]
(2, 2)


In [10]:
# aranging of no.s
c = np.arange(3,10)
print(c)
type(c)

[3 4 5 6 7 8 9]


numpy.ndarray

In [16]:
#use of a around()
b = np.array([1.345,3.224,4.1959])
print(np.around(np.sqrt(d),2))

[1.11 1.88 2.02]


In [14]:
# use of squareroot np.sqrt()
d = np.array([1.2345,3.5432,4.0912])
print(d)

print(type(d))

[1.2345 3.5432 4.0912]
<class 'numpy.ndarray'>


In [17]:
a3 = np.array([[2,3,4,5],[6,5,4, np.NAN]])
print(a3)
print(a3.shape)
print(a3.dtype)

[[ 2.  3.  4.  5.]
 [ 6.  5.  4. nan]]
(2, 4)
float64


In [18]:
a3.reshape(4,2)

array([[ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  5.],
       [ 4., nan]])

In [19]:
# mathematical operations
b1 = np.array([[3,4,6],[7,9,10],[4,6,12]])
b1

array([[ 3,  4,  6],
       [ 7,  9, 10],
       [ 4,  6, 12]])

In [20]:
print(b1.sum(axis = 1))
print(b1.sum(axis = 0))

[13 26 22]
[14 19 28]


In [21]:
print(b1.mean(axis = 1))
print(b1.mean(axis = 0))

[4.33333333 8.66666667 7.33333333]
[4.66666667 6.33333333 9.33333333]


In [23]:
# matrix operations
v = np.array([[3,4,6],[7,9,10],[4,6,12]])
print(v)
np.fill_diagonal(v,0)
print(v)

[[ 3  4  6]
 [ 7  9 10]
 [ 4  6 12]]
[[ 0  4  6]
 [ 7  0 10]
 [ 4  6  0]]


In [ ]:
# define 2 matrices and multyilpy 
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

